### ISSUE TITLE
Discrete Choice Model Capabilities

### ISSUE THREAD

**Issue by jiffyclub** [synthicity/activitysim#3]
[UrbanSim](https://github.com/synthicity/urbansim) has location choice models, but they are somewhat specialized to their application in real estate modeling. (For example, the LCMs always remove choices from the alternatives pool once they have been chosen.) As a first step toward adding models to ActibitySim we're working to generalize the discrete choice classes in UrbanSim so that they can be reused here. You can follow my work in the [dcm branch](https://github.com/synthicity/urbansim/tree/dcm) in UrbanSim.

Also related to this, we've added tests of UrbanSim's MNL implementation to make sure it matches R's mlogit package. You can see that work in synthicity/urbansim#132.

**Comment by fscottfoti** [comment]
Is there any reason not to merge the DCM branch on UrbanSim and close this issue?  I do use the changes in the MNL interaction in activitysim so it would be handy to depend on master rather than depending on the dcm branch.

**Comment by jiffyclub** [comment]
Yeah if you're using it let's merge it. I wasn't sure if any of the changes were actually being used.

**Comment by fscottfoti** [comment]
Sounds good - merge away!
