### ISSUE TITLE
user stories

### ISSUE THREAD

**Issue by fscottfoti** [synthicity/activitysim#31]
A suggestion was made on Friday to start making a list of "user stories," or perhaps more specifically, those things that users of the modeling system might want to change for different implementations or different scenarios.  These are things that we want to be able to change easily, version control those changes, and not have to change any core parts of the model system in order to do so.  Perhaps this issue can be the place to collect those stories?

**Comment by e-lo** [comment]
@fscottfoti  - it seems a little strange to put a bunch of user stories into a singular issue and have it stay open for eternity.

After the tests are suggested and decided upon in this issue, do you think we can create a .md document within the codebase that documents the "how to" for each of these stories?  If the "how to" is cumbersome for any of these stories, then that would be an indication that maybe this isn't the best way of doing things (or that there needs to be a significant upside in some other category).

An alternative would be to just list them in a wiki and come back to them every once and a while.  The downside here is that it isn't linked as elegantly to the code version.

**Comment by jiffyclub** [comment]
This sounds like a good use for [the wiki](https://github.com/synthicity/activitysim/wiki), which already has a lot of design related stuff in it. All of the ActivitySim stakeholders are collaborators on this repo (or can be added), so you should be able to edit the wiki. Documents from the wiki can be added to the main repo if the need arises.

**Comment by fscottfoti** [comment]
Makes sense to me.  I don't have a strong opinion as to where it should live, but the wiki seems like it would be slightly easier for non-coders.

**Comment by fscottfoti** [comment]
Moving to https://github.com/synthicity/activitysim/wiki/User-Stories
