### ISSUE TITLE
progress report

### ISSUE THREAD

**Issue by fscottfoti** [synthicity/activitysim#38]
As promised, here is my [progress report](https://github.com/synthicity/activitysim/wiki/Progress-Report) with percent completion for the code/modeling for each model.

There are a few different things that we might prioritize.
1) near completion of these models
2) near completion of the entire model set, with partially finished implementations of each model
3) continued work on the core, including some catch-up work moving some helper functions to the core and unit testing them and maybe getting a draft of documentation out
4) going straight at whatever we think is the "hardest" problem to make sure we can do it and then doing one of the above.  I think the hardest problem is probably the coordination of households (maybe in joint scheduling); others might think it's the computation burden required by running the full mode choice model.

I lean towards attacking the hardest problems (4), then catching up on unit testing (3), then doing a fairly complete implementation of the current model set (1) but am certainly open to alternatives.

**Comment by e-lo** [comment]
My non-vote is with 
1. get 'hard stuff' functionally working
2. get rest of models functionally working
3. profile code usability
4. profile code performance
