### ISSUE TITLE
Design decisions around low-level vs high-level objects, yaml vs. csv serialization, etc...

### ISSUE THREAD

**Issue by fscottfoti** [synthicity/activitysim#5]
The code in https://github.com/synthicity/activitysim/pull/4 already begs some interesting questions.  The biggest of which is how much to use the dcm code that Matt is currently working on.  As Matt and I discussed, dcm is primarily useful for serializing to YAML, for wrapping of low-level models inside larger segmented models and a few other small things.  

If we're not necessarily wed to YAML and if we're primarily interesting in simulation as opposed to estimation (early feedback from Dave Ory says this might be the case), and if we want to stick with the CSV/XLSX format for storing coefficients (which is nice when doing alternative specific coefficients because that's naturally 2D), then we're free to address this problem a little more directly using the other underlying utilities we have built.

https://github.com/synthicity/activitysim/blob/adding-defaults/example/models.py does exactly this.  The directness and conciseness of this approach is compelling.  We could potentially build up a new set of utilities with a slightly different set of design decisions *if we want to.*  At this time, the dependencies used from UrbanSim are essentially 1) the simulation framework for variables, tables, etc 2) low-level choice utilities from the urbanchoice directory and 3) utils.py for really nothing important.  We've discussed putting these in a different repo before so it's worth mentioning again in the context of this larger discussion.

**Comment by fscottfoti** [comment]
We should make a call on this pretty soon as to whether to allow specification of models in csv or stick with yaml.  I thought it would be helpful to be concrete - here is one of the model specifications converted from csv to yaml (you can also see the few lines it takes to convert csv to yaml if you're interested).  This is the kind of thing you can expect from a YAML representation: 1) row-by-row specification 2) repetition of column headers 3) the need to know yaml syntax and yes you can have syntax errors 4) no gui to change the formatting of columns 5) you will generally edit these things in your favorite text editor rather than excel.  If you want me to send a screenshot of the table in Excel I can do that, but I figured we can imagine what it looks like in Excel (but let me know if otherwise).

http://nbviewer.ipython.org/github/synthicity/activitysim/blob/cdap/notebooks/config_csv_to_yaml.ipynb

**Comment by fscottfoti** [comment]
I just realized the csv version of the file is available on github here

https://github.com/synthicity/activitysim/blob/cdap/example/configs/cdap_2_person.csv

**Comment by danielsclint** [comment]
I think based on our call before the break, we were in general agreement about moving forward with CSV. I think the general direction was to move forward with CSV until it clearly doesn't fit the mold anymore. Once we run into that problem, if at all, we could come back and re-evaluate the whether we convert to YAML or move forward with some type of hybrid approach.

It looks like switching between the two formats is pretty is on the input file side. How much impact inside the code to read the data format is there if we started with CSV and for some reason had to switch to YAML for everything?

**Comment by fscottfoti** [comment]
Sounds like a plan.  It will not be hard to switch from CSV to YAML for the specifications.  It will be slightly harder to go from Python to YAML if we prefer configuration files for the higher level model configuration, but only if we actually end up doing something non-standard in Python, which is rare.
